ktor:
  deployment:
    port: 80
  application:
    modules:
      - com.mospolytech.microservices.edugma.ApplicationKt.module

jwt:
  secret: $JWT_SECRET

postgres:
  url: $PG_URL
  driver: "org.postgresql.Driver"
  login: $PG_LOGIN
  password: $PG_PASSWORD

urls:
  getStudents: $GET_STUDENTS_URL
  getStaff: $GET_STAFF_URL

auth:
  getStudents: $GET_STUDENTS_AUTH
  getStaff: $GET_STAFF_AUTH

admin:
  key: $ADMIN_KEY
  logLevel: $LOG_LEVEL

mainlk:
  login: $MAIN_LK_LOGIN
  password: $MAIN_LK_PASSWORD
